@extends('layouts.admin')
@section('title', 'Salary · '.$salary->employee->name)
@section('page-title', $salary->employee->name.' · '.$salary->month->format('F Y'))
@section('page-action')<a href="{{ route('salaries.index') }}" class="btn btn-outline-secondary">Back to Salary</a>@endsection
@section('content')
<div class="card"><div class="card-body">
    <p class="text-muted small">Generated by {{ $salary->creator?->name ?? 'System' }} on {{ $salary->created_at->format('d M Y, h:i A') }}. The monthly rate and earned amount are saved with this salary.</p>
    @include('admin.salaries.partials.preview', $calculation)
</div></div>
<div class="row g-3"><div class="col-lg-6"><div class="card"><div class="card-header"><h4 class="card-title mb-0">Credit / debit entries this month</h4></div><div class="card-body">
    @forelse($advances as $advance)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $advance->paid_on->format('d M Y') }} · {{ $advance->entry_type === 'debit' ? 'Debit · returned' : 'Credit · paid' }} · {{ strtoupper($advance->method) }}<small class="d-block text-muted">{{ $advance->note }} · {{ $advance->creator?->name }}</small></span><strong>₹{{ \App\Support\SalaryMath::format($advance->amount_paise) }}</strong></div>
    @empty <p class="text-muted">No wallet entries this month.</p> @endforelse
</div></div></div><div class="col-lg-6"><div class="card"><div class="card-header"><h4 class="card-title mb-0">Salary payments</h4></div><div class="card-body">
    @forelse($salary->payments as $payment)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $payment->paid_on->format('d M Y') }} · {{ strtoupper($payment->method) }}<small class="d-block text-muted">{{ $payment->note }} · {{ $payment->creator?->name }}</small></span><strong>₹{{ \App\Support\SalaryMath::format($payment->amount_paise) }}</strong></div>
    @empty <p class="text-muted">No salary payments yet.</p> @endforelse
    @if(auth()->user()->role === 'admin' && $calculation['due'] > 0)
        <hr><form method="POST" action="{{ route('salaries.payment', $salary) }}" data-safe-submit>@csrf
            <div class="row g-2"><div class="col-sm-6"><label class="form-label">Payment date</label><input type="date" name="paid_on" max="{{ now()->toDateString() }}" value="{{ now()->toDateString() }}" class="form-control" required></div>
                <div class="col-sm-6"><label class="form-label">Amount (₹)</label><input type="number" name="amount_rupees" step="0.01" min="0.01" max="{{ number_format($calculation['due'] / 100, 2, '.', '') }}" class="form-control" required></div>
                <div class="col-sm-6"><label class="form-label">Method</label><select name="method" class="form-select"><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank">Bank</option><option value="other">Other</option></select></div>
                <div class="col-sm-6"><label class="form-label">Note</label><input name="note" maxlength="500" class="form-control"></div>
                <div class="col-12"><button class="btn btn-primary" data-submit-button><span class="spinner-border spinner-border-sm d-none" data-submit-spinner></span> <span data-submit-label>Record Payment</span></button></div>
            </div>
        </form>
    @endif
</div></div></div></div>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/people.css') }}">@endpush
@push('scripts')<script src="{{ asset('assets/js/record-form.js') }}" defer></script>@endpush
